name: Build
on:
  push:
    branches:
      - develop
  pull_request_target:

env:
  TEST_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TEST_REPO: ${{ github.repository }}
  TEST_SLACK_WEBHOOK_URL: ${{ secrets.TEST_SLACK_WEBHOOK_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: npm ci
      - name: Build Image
        run: npm run docker-build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: asdf_install
        uses: asdf-vm/actions/install@v3
      - name: Install dependencies
        run: (cd reminder && npm ci)
      - name: Run tests Image
        run: (cd reminder && npm run test)
          
